// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance_audit.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAttendanceAudit = `-- name: CountAttendanceAudit :one
SELECT COUNT(*) FROM attendance_records
WHERE tenant_id = $1
  AND ($2::bigint IS NULL OR user_id = $2)
  AND ($3::date IS NULL OR work_date >= $3)
  AND ($4::date IS NULL OR work_date <= $4)
  AND ($5::text IS NULL OR source::text = $5)
  AND ($6::text IS NULL OR host(client_ip) = $6)
`

type CountAttendanceAuditParams struct {
	TenantID int64       `json:"tenant_id"`
	UserID   pgtype.Int8 `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
	Source   pgtype.Text `json:"source"`
	ClientIp pgtype.Text `json:"client_ip"`
}

func (q *Queries) CountAttendanceAudit(ctx context.Context, arg CountAttendanceAuditParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAttendanceAudit,
		arg.TenantID,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
		arg.Source,
		arg.ClientIp,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchAttendanceAudit = `-- name: SearchAttendanceAudit :many

SELECT id, tenant_id, user_id, work_date, check_in_at, check_out_at,
       lunch_break_minutes, source, client_ip, user_agent, status,
       created_at, updated_at
FROM attendance_records
WHERE tenant_id = $1
  AND ($2::bigint IS NULL OR user_id = $2)
  AND ($3::date IS NULL OR work_date >= $3)
  AND ($4::date IS NULL OR work_date <= $4)
  AND ($5::text IS NULL OR source::text = $5)
  AND ($6::text IS NULL OR host(client_ip) = $6)
ORDER BY work_date DESC, user_id ASC, id ASC
LIMIT $8 OFFSET $7
`

type SearchAttendanceAuditParams struct {
	TenantID int64       `json:"tenant_id"`
	UserID   pgtype.Int8 `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
	Source   pgtype.Text `json:"source"`
	ClientIp pgtype.Text `json:"client_ip"`
	Off      int32       `json:"off"`
	Lim      int32       `json:"lim"`
}

// Sprint 9: 출퇴근 감사 로그 조회 — HR/super_admin only.
// 본 쿼리는 attendance_records 위에서 SELECT only (Sprint 4 BE 의 attendance.sql 와 분리).
// nullable filter pattern: sqlc.narg() 가 NULL 이면 해당 필터 무시.
//   - 사용자 / 기간 / source / client_ip 필터 조합.
//   - client_ip 는 INET 컬럼 → host(client_ip) 로 텍스트 매칭 (CIDR 매칭 미사용 — 정확 일치).
func (q *Queries) SearchAttendanceAudit(ctx context.Context, arg SearchAttendanceAuditParams) ([]AttendanceRecord, error) {
	rows, err := q.db.Query(ctx, searchAttendanceAudit,
		arg.TenantID,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
		arg.Source,
		arg.ClientIp,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttendanceRecord
	for rows.Next() {
		var i AttendanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.WorkDate,
			&i.CheckInAt,
			&i.CheckOutAt,
			&i.LunchBreakMinutes,
			&i.Source,
			&i.ClientIp,
			&i.UserAgent,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
