// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance.sql

package dbq

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttendanceCheckIn = `-- name: CreateAttendanceCheckIn :one
INSERT INTO attendance_records (
    tenant_id, user_id, work_date, check_in_at,
    source, client_ip, user_agent, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, user_id, work_date, check_in_at, check_out_at,
          lunch_break_minutes, source, client_ip, user_agent, status,
          created_at, updated_at
`

type CreateAttendanceCheckInParams struct {
	TenantID  int64              `json:"tenant_id"`
	UserID    int64              `json:"user_id"`
	WorkDate  pgtype.Date        `json:"work_date"`
	CheckInAt pgtype.Timestamptz `json:"check_in_at"`
	Source    AttendanceSource   `json:"source"`
	ClientIp  *netip.Addr        `json:"client_ip"`
	UserAgent pgtype.Text        `json:"user_agent"`
	Status    AttendanceStatus   `json:"status"`
}

func (q *Queries) CreateAttendanceCheckIn(ctx context.Context, arg CreateAttendanceCheckInParams) (AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, createAttendanceCheckIn,
		arg.TenantID,
		arg.UserID,
		arg.WorkDate,
		arg.CheckInAt,
		arg.Source,
		arg.ClientIp,
		arg.UserAgent,
		arg.Status,
	)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.WorkDate,
		&i.CheckInAt,
		&i.CheckOutAt,
		&i.LunchBreakMinutes,
		&i.Source,
		&i.ClientIp,
		&i.UserAgent,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttendanceByUserDate = `-- name: GetAttendanceByUserDate :one
SELECT id, tenant_id, user_id, work_date, check_in_at, check_out_at,
       lunch_break_minutes, source, client_ip, user_agent, status,
       created_at, updated_at
FROM attendance_records
WHERE user_id = $1
  AND work_date = $2
  AND tenant_id = $3
`

type GetAttendanceByUserDateParams struct {
	UserID   int64       `json:"user_id"`
	WorkDate pgtype.Date `json:"work_date"`
	TenantID int64       `json:"tenant_id"`
}

func (q *Queries) GetAttendanceByUserDate(ctx context.Context, arg GetAttendanceByUserDateParams) (AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, getAttendanceByUserDate, arg.UserID, arg.WorkDate, arg.TenantID)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.WorkDate,
		&i.CheckInAt,
		&i.CheckOutAt,
		&i.LunchBreakMinutes,
		&i.Source,
		&i.ClientIp,
		&i.UserAgent,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOpenAttendanceForDate = `-- name: ListOpenAttendanceForDate :many
SELECT id, tenant_id, user_id, work_date, check_in_at, check_out_at,
       lunch_break_minutes, source, client_ip, user_agent, status,
       created_at, updated_at
FROM attendance_records
WHERE work_date = $1
  AND check_out_at IS NULL
  AND status <> 'auto_closed'
ORDER BY id ASC
`

// 자정 KST cron 이 사용. work_date = yesterday(KST) AND check_out_at IS NULL.
func (q *Queries) ListOpenAttendanceForDate(ctx context.Context, workDate pgtype.Date) ([]AttendanceRecord, error) {
	rows, err := q.db.Query(ctx, listOpenAttendanceForDate, workDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttendanceRecord
	for rows.Next() {
		var i AttendanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.WorkDate,
			&i.CheckInAt,
			&i.CheckOutAt,
			&i.LunchBreakMinutes,
			&i.Source,
			&i.ClientIp,
			&i.UserAgent,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttendanceAutoClosed = `-- name: MarkAttendanceAutoClosed :exec
UPDATE attendance_records
SET status = 'auto_closed',
    updated_at = now()
WHERE id = ANY($1::bigint[])
`

// 자정 cron 이 호출. check_out_at 은 NULL 유지, status 만 auto_closed 로 마킹.
func (q *Queries) MarkAttendanceAutoClosed(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, markAttendanceAutoClosed, ids)
	return err
}

const updateAttendanceCheckOut = `-- name: UpdateAttendanceCheckOut :one
UPDATE attendance_records
SET check_out_at = $1,
    status = $2,
    updated_at = now()
WHERE id = $3
  AND tenant_id = $4
RETURNING id, tenant_id, user_id, work_date, check_in_at, check_out_at,
          lunch_break_minutes, source, client_ip, user_agent, status,
          created_at, updated_at
`

type UpdateAttendanceCheckOutParams struct {
	CheckOutAt pgtype.Timestamptz `json:"check_out_at"`
	Status     AttendanceStatus   `json:"status"`
	ID         int64              `json:"id"`
	TenantID   int64              `json:"tenant_id"`
}

func (q *Queries) UpdateAttendanceCheckOut(ctx context.Context, arg UpdateAttendanceCheckOutParams) (AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, updateAttendanceCheckOut,
		arg.CheckOutAt,
		arg.Status,
		arg.ID,
		arg.TenantID,
	)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.WorkDate,
		&i.CheckInAt,
		&i.CheckOutAt,
		&i.LunchBreakMinutes,
		&i.Source,
		&i.ClientIp,
		&i.UserAgent,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
