// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLeaveBalanceAdjustment = `-- name: CreateLeaveBalanceAdjustment :one
INSERT INTO leave_balance_adjustments (tenant_id, balance_id, actor_user_id, delta_hours, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, balance_id, actor_user_id, delta_hours, reason, created_at
`

type CreateLeaveBalanceAdjustmentParams struct {
	TenantID    int64          `json:"tenant_id"`
	BalanceID   int64          `json:"balance_id"`
	ActorUserID int64          `json:"actor_user_id"`
	DeltaHours  pgtype.Numeric `json:"delta_hours"`
	Reason      string         `json:"reason"`
}

func (q *Queries) CreateLeaveBalanceAdjustment(ctx context.Context, arg CreateLeaveBalanceAdjustmentParams) (LeaveBalanceAdjustment, error) {
	row := q.db.QueryRow(ctx, createLeaveBalanceAdjustment,
		arg.TenantID,
		arg.BalanceID,
		arg.ActorUserID,
		arg.DeltaHours,
		arg.Reason,
	)
	var i LeaveBalanceAdjustment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BalanceID,
		&i.ActorUserID,
		&i.DeltaHours,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveUsersForAccrual = `-- name: ListActiveUsersForAccrual :many
SELECT id, tenant_id, email, password_hash, name, status, team_id, manager_id,
       hire_date, role, work_start_time, work_end_time, token_version,
       created_at, updated_at, deleted_at
FROM users
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND status = 'active'
ORDER BY id ASC
`

func (q *Queries) ListActiveUsersForAccrual(ctx context.Context, tenantID int64) ([]User, error) {
	rows, err := q.db.Query(ctx, listActiveUsersForAccrual, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Status,
			&i.TeamID,
			&i.ManagerID,
			&i.HireDate,
			&i.Role,
			&i.WorkStartTime,
			&i.WorkEndTime,
			&i.TokenVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaveBalanceAdjustments = `-- name: ListLeaveBalanceAdjustments :many
SELECT id, tenant_id, balance_id, actor_user_id, delta_hours, reason, created_at
FROM leave_balance_adjustments
WHERE balance_id = $1
  AND tenant_id = $2
ORDER BY created_at DESC
`

type ListLeaveBalanceAdjustmentsParams struct {
	BalanceID int64 `json:"balance_id"`
	TenantID  int64 `json:"tenant_id"`
}

func (q *Queries) ListLeaveBalanceAdjustments(ctx context.Context, arg ListLeaveBalanceAdjustmentsParams) ([]LeaveBalanceAdjustment, error) {
	rows, err := q.db.Query(ctx, listLeaveBalanceAdjustments, arg.BalanceID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveBalanceAdjustment
	for rows.Next() {
		var i LeaveBalanceAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BalanceID,
			&i.ActorUserID,
			&i.DeltaHours,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseAdvisoryLockAccrual = `-- name: ReleaseAdvisoryLockAccrual :one
SELECT pg_advisory_unlock($1::bigint) AS released
`

func (q *Queries) ReleaseAdvisoryLockAccrual(ctx context.Context, dollar_1 int64) (bool, error) {
	row := q.db.QueryRow(ctx, releaseAdvisoryLockAccrual, dollar_1)
	var released bool
	err := row.Scan(&released)
	return released, err
}

const tryAdvisoryLockAccrual = `-- name: TryAdvisoryLockAccrual :one
SELECT pg_try_advisory_lock($1::bigint) AS acquired
`

func (q *Queries) TryAdvisoryLockAccrual(ctx context.Context, dollar_1 int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryAdvisoryLockAccrual, dollar_1)
	var acquired bool
	err := row.Scan(&acquired)
	return acquired, err
}
