// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendar.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCalendarAttendances = `-- name: ListCalendarAttendances :many
SELECT id, tenant_id, user_id, work_date, check_in_at, check_out_at,
       lunch_break_minutes, source, status
FROM attendance_records
WHERE tenant_id = $1
  AND user_id   = $2
  AND work_date >= $3
  AND work_date <= $4
ORDER BY work_date ASC, id ASC
`

type ListCalendarAttendancesParams struct {
	TenantID int64       `json:"tenant_id"`
	UserID   int64       `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type ListCalendarAttendancesRow struct {
	ID                int64              `json:"id"`
	TenantID          int64              `json:"tenant_id"`
	UserID            int64              `json:"user_id"`
	WorkDate          pgtype.Date        `json:"work_date"`
	CheckInAt         pgtype.Timestamptz `json:"check_in_at"`
	CheckOutAt        pgtype.Timestamptz `json:"check_out_at"`
	LunchBreakMinutes int32              `json:"lunch_break_minutes"`
	Source            AttendanceSource   `json:"source"`
	Status            AttendanceStatus   `json:"status"`
}

// 본인 출퇴근만 노출 — user_id 를 필수 필터로 받는다.
func (q *Queries) ListCalendarAttendances(ctx context.Context, arg ListCalendarAttendancesParams) ([]ListCalendarAttendancesRow, error) {
	rows, err := q.db.Query(ctx, listCalendarAttendances,
		arg.TenantID,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCalendarAttendancesRow
	for rows.Next() {
		var i ListCalendarAttendancesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.WorkDate,
			&i.CheckInAt,
			&i.CheckOutAt,
			&i.LunchBreakMinutes,
			&i.Source,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarLeaves = `-- name: ListCalendarLeaves :many

SELECT lr.id, lr.tenant_id, lr.requester_id, lr.leave_type_id,
       lr.start_at, lr.end_at, lr.hours, lr.reason, lr.status, lr.approver_id,
       u.name AS requester_name,
       lt.code AS leave_type_code,
       lt.name AS leave_type_name
FROM leave_requests lr
JOIN users u ON u.id = lr.requester_id AND u.tenant_id = lr.tenant_id
JOIN leave_types lt ON lt.id = lr.leave_type_id AND lt.tenant_id = lr.tenant_id
WHERE lr.tenant_id = $1
  AND lr.status IN ('pending', 'approved')
  AND lr.start_at < $2
  AND lr.end_at   > $3
ORDER BY lr.start_at ASC, lr.id ASC
`

type ListCalendarLeavesParams struct {
	TenantID int64              `json:"tenant_id"`
	ToAt     pgtype.Timestamptz `json:"to_at"`
	FromAt   pgtype.Timestamptz `json:"from_at"`
}

type ListCalendarLeavesRow struct {
	ID            int64              `json:"id"`
	TenantID      int64              `json:"tenant_id"`
	RequesterID   int64              `json:"requester_id"`
	LeaveTypeID   int64              `json:"leave_type_id"`
	StartAt       pgtype.Timestamptz `json:"start_at"`
	EndAt         pgtype.Timestamptz `json:"end_at"`
	Hours         pgtype.Numeric     `json:"hours"`
	Reason        pgtype.Text        `json:"reason"`
	Status        LeaveRequestStatus `json:"status"`
	ApproverID    pgtype.Int8        `json:"approver_id"`
	RequesterName string             `json:"requester_name"`
	LeaveTypeCode string             `json:"leave_type_code"`
	LeaveTypeName string             `json:"leave_type_name"`
}

// Sprint 8: 공유 캘린더 view.
//
// 가시성 규칙 (plan.md §아키텍처 결정 — 캘린더 가시성):
//   - 휴가 날짜 + 종류 : 전사 (모든 직원).
//   - 휴가 사유       : 본인 + 결재자 + HR/super_admin 만 (service layer 에서 마스킹).
//   - 본인 출퇴근만   : scope='me' 또는 본인 row 만 노출.
//
// 본 쿼리는 raw row 를 모두 반환하고, application layer 에서 사유 마스킹을 한다.
// 범위 내 휴가 (pending + approved). cancelled / rejected 는 제외.
// 신청자 이름 / 휴가 종류 code/name 까지 join 으로 가져온다.
func (q *Queries) ListCalendarLeaves(ctx context.Context, arg ListCalendarLeavesParams) ([]ListCalendarLeavesRow, error) {
	rows, err := q.db.Query(ctx, listCalendarLeaves, arg.TenantID, arg.ToAt, arg.FromAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCalendarLeavesRow
	for rows.Next() {
		var i ListCalendarLeavesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RequesterID,
			&i.LeaveTypeID,
			&i.StartAt,
			&i.EndAt,
			&i.Hours,
			&i.Reason,
			&i.Status,
			&i.ApproverID,
			&i.RequesterName,
			&i.LeaveTypeCode,
			&i.LeaveTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
