// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delegations.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDelegation = `-- name: CreateDelegation :one

INSERT INTO delegations (tenant_id, delegator_id, delegate_id, valid_from, valid_to, scope)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, delegator_id, delegate_id, valid_from, valid_to, scope, created_at
`

type CreateDelegationParams struct {
	TenantID    int64              `json:"tenant_id"`
	DelegatorID int64              `json:"delegator_id"`
	DelegateID  int64              `json:"delegate_id"`
	ValidFrom   pgtype.Timestamptz `json:"valid_from"`
	ValidTo     pgtype.Timestamptz `json:"valid_to"`
	Scope       []byte             `json:"scope"`
}

// Sprint 6: delegations CRUD + 활성 위임 조회.
func (q *Queries) CreateDelegation(ctx context.Context, arg CreateDelegationParams) (Delegation, error) {
	row := q.db.QueryRow(ctx, createDelegation,
		arg.TenantID,
		arg.DelegatorID,
		arg.DelegateID,
		arg.ValidFrom,
		arg.ValidTo,
		arg.Scope,
	)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DelegatorID,
		&i.DelegateID,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Scope,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDelegation = `-- name: DeleteDelegation :exec
DELETE FROM delegations
WHERE id = $1
  AND tenant_id = $2
  AND delegator_id = $3
`

type DeleteDelegationParams struct {
	ID          int64 `json:"id"`
	TenantID    int64 `json:"tenant_id"`
	DelegatorID int64 `json:"delegator_id"`
}

func (q *Queries) DeleteDelegation(ctx context.Context, arg DeleteDelegationParams) error {
	_, err := q.db.Exec(ctx, deleteDelegation, arg.ID, arg.TenantID, arg.DelegatorID)
	return err
}

const getDelegationByID = `-- name: GetDelegationByID :one
SELECT id, tenant_id, delegator_id, delegate_id, valid_from, valid_to, scope, created_at
FROM delegations
WHERE id = $1
  AND tenant_id = $2
`

type GetDelegationByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetDelegationByID(ctx context.Context, arg GetDelegationByIDParams) (Delegation, error) {
	row := q.db.QueryRow(ctx, getDelegationByID, arg.ID, arg.TenantID)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DelegatorID,
		&i.DelegateID,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Scope,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveDelegationsByDelegator = `-- name: ListActiveDelegationsByDelegator :many
SELECT id, tenant_id, delegator_id, delegate_id, valid_from, valid_to, scope, created_at
FROM delegations
WHERE delegator_id = $1
  AND tenant_id = $2
  AND valid_from <= $3
  AND valid_to >= $3
ORDER BY valid_from DESC, id DESC
`

type ListActiveDelegationsByDelegatorParams struct {
	DelegatorID int64              `json:"delegator_id"`
	TenantID    int64              `json:"tenant_id"`
	ValidFrom   pgtype.Timestamptz `json:"valid_from"`
}

// Sprint 6 resolver — approver_id 결정 시점에 활성 위임 매칭.
// valid_from <= at <= valid_to.
func (q *Queries) ListActiveDelegationsByDelegator(ctx context.Context, arg ListActiveDelegationsByDelegatorParams) ([]Delegation, error) {
	rows, err := q.db.Query(ctx, listActiveDelegationsByDelegator, arg.DelegatorID, arg.TenantID, arg.ValidFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delegation
	for rows.Next() {
		var i Delegation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DelegatorID,
			&i.DelegateID,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Scope,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDelegationsByDelegator = `-- name: ListDelegationsByDelegator :many
SELECT id, tenant_id, delegator_id, delegate_id, valid_from, valid_to, scope, created_at
FROM delegations
WHERE delegator_id = $1
  AND tenant_id = $2
ORDER BY valid_from DESC, id DESC
`

type ListDelegationsByDelegatorParams struct {
	DelegatorID int64 `json:"delegator_id"`
	TenantID    int64 `json:"tenant_id"`
}

func (q *Queries) ListDelegationsByDelegator(ctx context.Context, arg ListDelegationsByDelegatorParams) ([]Delegation, error) {
	rows, err := q.db.Query(ctx, listDelegationsByDelegator, arg.DelegatorID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delegation
	for rows.Next() {
		var i Delegation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DelegatorID,
			&i.DelegateID,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Scope,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
