// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expense_reports.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelExpenseReport = `-- name: CancelExpenseReport :one
UPDATE expense_reports
SET status = 'cancelled',
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
  AND requester_id = $3
  AND status = 'pending'
RETURNING id, tenant_id, requester_id, amount_won, vendor, purpose, paid_at, attachment_url,
          status, approver_id, decided_at, decision_comment, created_at, updated_at
`

type CancelExpenseReportParams struct {
	ID          int64 `json:"id"`
	TenantID    int64 `json:"tenant_id"`
	RequesterID int64 `json:"requester_id"`
}

// Cancel — 본인이 pending 상태일 때만. WHERE status='pending' 으로 race 방지.
func (q *Queries) CancelExpenseReport(ctx context.Context, arg CancelExpenseReportParams) (ExpenseReport, error) {
	row := q.db.QueryRow(ctx, cancelExpenseReport, arg.ID, arg.TenantID, arg.RequesterID)
	var i ExpenseReport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequesterID,
		&i.AmountWon,
		&i.Vendor,
		&i.Purpose,
		&i.PaidAt,
		&i.AttachmentUrl,
		&i.Status,
		&i.ApproverID,
		&i.DecidedAt,
		&i.DecisionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countExpenseReportsByRequester = `-- name: CountExpenseReportsByRequester :one
SELECT COUNT(*) FROM expense_reports
WHERE requester_id = $1
  AND tenant_id = $2
`

type CountExpenseReportsByRequesterParams struct {
	RequesterID int64 `json:"requester_id"`
	TenantID    int64 `json:"tenant_id"`
}

func (q *Queries) CountExpenseReportsByRequester(ctx context.Context, arg CountExpenseReportsByRequesterParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpenseReportsByRequester, arg.RequesterID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingExpenseReportsByApprover = `-- name: CountPendingExpenseReportsByApprover :one
SELECT COUNT(*) FROM expense_reports
WHERE approver_id = $1
  AND tenant_id = $2
  AND status = 'pending'
`

type CountPendingExpenseReportsByApproverParams struct {
	ApproverID pgtype.Int8 `json:"approver_id"`
	TenantID   int64       `json:"tenant_id"`
}

func (q *Queries) CountPendingExpenseReportsByApprover(ctx context.Context, arg CountPendingExpenseReportsByApproverParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingExpenseReportsByApprover, arg.ApproverID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpenseReport = `-- name: CreateExpenseReport :one
INSERT INTO expense_reports (tenant_id, requester_id, amount_won, vendor, purpose, paid_at,
                              approver_id, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending')
RETURNING id, tenant_id, requester_id, amount_won, vendor, purpose, paid_at, attachment_url,
          status, approver_id, decided_at, decision_comment, created_at, updated_at
`

type CreateExpenseReportParams struct {
	TenantID    int64       `json:"tenant_id"`
	RequesterID int64       `json:"requester_id"`
	AmountWon   int64       `json:"amount_won"`
	Vendor      string      `json:"vendor"`
	Purpose     string      `json:"purpose"`
	PaidAt      pgtype.Date `json:"paid_at"`
	ApproverID  pgtype.Int8 `json:"approver_id"`
}

func (q *Queries) CreateExpenseReport(ctx context.Context, arg CreateExpenseReportParams) (ExpenseReport, error) {
	row := q.db.QueryRow(ctx, createExpenseReport,
		arg.TenantID,
		arg.RequesterID,
		arg.AmountWon,
		arg.Vendor,
		arg.Purpose,
		arg.PaidAt,
		arg.ApproverID,
	)
	var i ExpenseReport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequesterID,
		&i.AmountWon,
		&i.Vendor,
		&i.Purpose,
		&i.PaidAt,
		&i.AttachmentUrl,
		&i.Status,
		&i.ApproverID,
		&i.DecidedAt,
		&i.DecisionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseReportByID = `-- name: GetExpenseReportByID :one

SELECT id, tenant_id, requester_id, amount_won, vendor, purpose, paid_at, attachment_url,
       status, approver_id, decided_at, decision_comment, created_at, updated_at
FROM expense_reports
WHERE id = $1
  AND tenant_id = $2
`

type GetExpenseReportByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

// Sprint 7: expense_reports CRUD + 결재 상태 전이 + 첨부 URL 업데이트.
func (q *Queries) GetExpenseReportByID(ctx context.Context, arg GetExpenseReportByIDParams) (ExpenseReport, error) {
	row := q.db.QueryRow(ctx, getExpenseReportByID, arg.ID, arg.TenantID)
	var i ExpenseReport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequesterID,
		&i.AmountWon,
		&i.Vendor,
		&i.Purpose,
		&i.PaidAt,
		&i.AttachmentUrl,
		&i.Status,
		&i.ApproverID,
		&i.DecidedAt,
		&i.DecisionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseReportForUpdate = `-- name: GetExpenseReportForUpdate :one
SELECT id, tenant_id, requester_id, amount_won, vendor, purpose, paid_at, attachment_url,
       status, approver_id, decided_at, decision_comment, created_at, updated_at
FROM expense_reports
WHERE id = $1
  AND tenant_id = $2
FOR UPDATE
`

type GetExpenseReportForUpdateParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

// Approve/Reject 트랜잭션 내부 — SELECT FOR UPDATE 로 동시성 보호.
func (q *Queries) GetExpenseReportForUpdate(ctx context.Context, arg GetExpenseReportForUpdateParams) (ExpenseReport, error) {
	row := q.db.QueryRow(ctx, getExpenseReportForUpdate, arg.ID, arg.TenantID)
	var i ExpenseReport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequesterID,
		&i.AmountWon,
		&i.Vendor,
		&i.Purpose,
		&i.PaidAt,
		&i.AttachmentUrl,
		&i.Status,
		&i.ApproverID,
		&i.DecidedAt,
		&i.DecisionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpenseReportsByRequester = `-- name: ListExpenseReportsByRequester :many
SELECT id, tenant_id, requester_id, amount_won, vendor, purpose, paid_at, attachment_url,
       status, approver_id, decided_at, decision_comment, created_at, updated_at
FROM expense_reports
WHERE requester_id = $1
  AND tenant_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListExpenseReportsByRequesterParams struct {
	RequesterID int64 `json:"requester_id"`
	TenantID    int64 `json:"tenant_id"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

func (q *Queries) ListExpenseReportsByRequester(ctx context.Context, arg ListExpenseReportsByRequesterParams) ([]ExpenseReport, error) {
	rows, err := q.db.Query(ctx, listExpenseReportsByRequester,
		arg.RequesterID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseReport
	for rows.Next() {
		var i ExpenseReport
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RequesterID,
			&i.AmountWon,
			&i.Vendor,
			&i.Purpose,
			&i.PaidAt,
			&i.AttachmentUrl,
			&i.Status,
			&i.ApproverID,
			&i.DecidedAt,
			&i.DecisionComment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingExpenseReportsByApprover = `-- name: ListPendingExpenseReportsByApprover :many
SELECT id, tenant_id, requester_id, amount_won, vendor, purpose, paid_at, attachment_url,
       status, approver_id, decided_at, decision_comment, created_at, updated_at
FROM expense_reports
WHERE approver_id = $1
  AND tenant_id = $2
  AND status = 'pending'
ORDER BY created_at ASC, id ASC
LIMIT $3 OFFSET $4
`

type ListPendingExpenseReportsByApproverParams struct {
	ApproverID pgtype.Int8 `json:"approver_id"`
	TenantID   int64       `json:"tenant_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

// 결재자 대기함. approver_id 매칭 + status='pending'.
func (q *Queries) ListPendingExpenseReportsByApprover(ctx context.Context, arg ListPendingExpenseReportsByApproverParams) ([]ExpenseReport, error) {
	rows, err := q.db.Query(ctx, listPendingExpenseReportsByApprover,
		arg.ApproverID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseReport
	for rows.Next() {
		var i ExpenseReport
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RequesterID,
			&i.AmountWon,
			&i.Vendor,
			&i.Purpose,
			&i.PaidAt,
			&i.AttachmentUrl,
			&i.Status,
			&i.ApproverID,
			&i.DecidedAt,
			&i.DecisionComment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpenseReportAttachment = `-- name: UpdateExpenseReportAttachment :one
UPDATE expense_reports
SET attachment_url = $3,
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, requester_id, amount_won, vendor, purpose, paid_at, attachment_url,
          status, approver_id, decided_at, decision_comment, created_at, updated_at
`

type UpdateExpenseReportAttachmentParams struct {
	ID            int64       `json:"id"`
	TenantID      int64       `json:"tenant_id"`
	AttachmentUrl pgtype.Text `json:"attachment_url"`
}

// 첨부 업로드 후 url 갱신. 본인만 호출 가능 (handler 권한 검증).
func (q *Queries) UpdateExpenseReportAttachment(ctx context.Context, arg UpdateExpenseReportAttachmentParams) (ExpenseReport, error) {
	row := q.db.QueryRow(ctx, updateExpenseReportAttachment, arg.ID, arg.TenantID, arg.AttachmentUrl)
	var i ExpenseReport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequesterID,
		&i.AmountWon,
		&i.Vendor,
		&i.Purpose,
		&i.PaidAt,
		&i.AttachmentUrl,
		&i.Status,
		&i.ApproverID,
		&i.DecidedAt,
		&i.DecisionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExpenseReportDecision = `-- name: UpdateExpenseReportDecision :one
UPDATE expense_reports
SET status = $3,
    approver_id = $4,
    decided_at = $5,
    decision_comment = $6,
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, requester_id, amount_won, vendor, purpose, paid_at, attachment_url,
          status, approver_id, decided_at, decision_comment, created_at, updated_at
`

type UpdateExpenseReportDecisionParams struct {
	ID              int64              `json:"id"`
	TenantID        int64              `json:"tenant_id"`
	Status          LeaveRequestStatus `json:"status"`
	ApproverID      pgtype.Int8        `json:"approver_id"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	DecisionComment pgtype.Text        `json:"decision_comment"`
}

// Approve/Reject 공용 — status + approver_id + decided_at + decision_comment 업데이트.
func (q *Queries) UpdateExpenseReportDecision(ctx context.Context, arg UpdateExpenseReportDecisionParams) (ExpenseReport, error) {
	row := q.db.QueryRow(ctx, updateExpenseReportDecision,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.ApproverID,
		arg.DecidedAt,
		arg.DecisionComment,
	)
	var i ExpenseReport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequesterID,
		&i.AmountWon,
		&i.Vendor,
		&i.Purpose,
		&i.PaidAt,
		&i.AttachmentUrl,
		&i.Status,
		&i.ApproverID,
		&i.DecidedAt,
		&i.DecisionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
