// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: holidays.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHolidays = `-- name: CountHolidays :one
SELECT COUNT(*) FROM holidays
WHERE tenant_id = $1
`

func (q *Queries) CountHolidays(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countHolidays, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getHolidayByID = `-- name: GetHolidayByID :one
SELECT id, tenant_id, date, name, is_recurring, country_code, created_at
FROM holidays
WHERE id = $1
  AND tenant_id = $2
`

type GetHolidayByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetHolidayByID(ctx context.Context, arg GetHolidayByIDParams) (Holiday, error) {
	row := q.db.QueryRow(ctx, getHolidayByID, arg.ID, arg.TenantID)
	var i Holiday
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Date,
		&i.Name,
		&i.IsRecurring,
		&i.CountryCode,
		&i.CreatedAt,
	)
	return i, err
}

const listHolidays = `-- name: ListHolidays :many
SELECT id, tenant_id, date, name, is_recurring, country_code, created_at
FROM holidays
WHERE tenant_id = $1
ORDER BY date ASC
`

func (q *Queries) ListHolidays(ctx context.Context, tenantID int64) ([]Holiday, error) {
	rows, err := q.db.Query(ctx, listHolidays, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Holiday
	for rows.Next() {
		var i Holiday
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Date,
			&i.Name,
			&i.IsRecurring,
			&i.CountryCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHolidaysInRange = `-- name: ListHolidaysInRange :many
SELECT id, tenant_id, date, name, is_recurring, country_code, created_at
FROM holidays
WHERE tenant_id = $1
  AND date >= $2
  AND date <= $3
ORDER BY date ASC
`

type ListHolidaysInRangeParams struct {
	TenantID int64       `json:"tenant_id"`
	Date     pgtype.Date `json:"date"`
	Date_2   pgtype.Date `json:"date_2"`
}

func (q *Queries) ListHolidaysInRange(ctx context.Context, arg ListHolidaysInRangeParams) ([]Holiday, error) {
	rows, err := q.db.Query(ctx, listHolidaysInRange, arg.TenantID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Holiday
	for rows.Next() {
		var i Holiday
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Date,
			&i.Name,
			&i.IsRecurring,
			&i.CountryCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
