// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leave_balances.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustLeaveBalanceHours = `-- name: AdjustLeaveBalanceHours :one
UPDATE leave_balances
SET granted_hours = granted_hours + $1::numeric,
    updated_at = now()
WHERE id = $2
  AND tenant_id = $3
RETURNING id, tenant_id, user_id, leave_type_id, period_year,
          granted_hours, used_hours, expires_at,
          created_at, updated_at
`

type AdjustLeaveBalanceHoursParams struct {
	DeltaHours pgtype.Numeric `json:"delta_hours"`
	ID         int64          `json:"id"`
	TenantID   int64          `json:"tenant_id"`
}

func (q *Queries) AdjustLeaveBalanceHours(ctx context.Context, arg AdjustLeaveBalanceHoursParams) (LeaveBalance, error) {
	row := q.db.QueryRow(ctx, adjustLeaveBalanceHours, arg.DeltaHours, arg.ID, arg.TenantID)
	var i LeaveBalance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.LeaveTypeID,
		&i.PeriodYear,
		&i.GrantedHours,
		&i.UsedHours,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeaveBalanceByID = `-- name: GetLeaveBalanceByID :one
SELECT id, tenant_id, user_id, leave_type_id, period_year,
       granted_hours, used_hours, expires_at,
       created_at, updated_at
FROM leave_balances
WHERE id = $1
  AND tenant_id = $2
`

type GetLeaveBalanceByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetLeaveBalanceByID(ctx context.Context, arg GetLeaveBalanceByIDParams) (LeaveBalance, error) {
	row := q.db.QueryRow(ctx, getLeaveBalanceByID, arg.ID, arg.TenantID)
	var i LeaveBalance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.LeaveTypeID,
		&i.PeriodYear,
		&i.GrantedHours,
		&i.UsedHours,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeaveBalanceForUserTypeYear = `-- name: GetLeaveBalanceForUserTypeYear :one
SELECT id, tenant_id, user_id, leave_type_id, period_year,
       granted_hours, used_hours, expires_at,
       created_at, updated_at
FROM leave_balances
WHERE user_id = $1
  AND leave_type_id = $2
  AND period_year = $3
  AND tenant_id = $4
`

type GetLeaveBalanceForUserTypeYearParams struct {
	UserID      int64 `json:"user_id"`
	LeaveTypeID int64 `json:"leave_type_id"`
	PeriodYear  int32 `json:"period_year"`
	TenantID    int64 `json:"tenant_id"`
}

func (q *Queries) GetLeaveBalanceForUserTypeYear(ctx context.Context, arg GetLeaveBalanceForUserTypeYearParams) (LeaveBalance, error) {
	row := q.db.QueryRow(ctx, getLeaveBalanceForUserTypeYear,
		arg.UserID,
		arg.LeaveTypeID,
		arg.PeriodYear,
		arg.TenantID,
	)
	var i LeaveBalance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.LeaveTypeID,
		&i.PeriodYear,
		&i.GrantedHours,
		&i.UsedHours,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLeaveBalancesByUser = `-- name: ListLeaveBalancesByUser :many
SELECT id, tenant_id, user_id, leave_type_id, period_year,
       granted_hours, used_hours, expires_at,
       created_at, updated_at
FROM leave_balances
WHERE user_id = $1
  AND tenant_id = $2
ORDER BY period_year DESC, leave_type_id ASC
`

type ListLeaveBalancesByUserParams struct {
	UserID   int64 `json:"user_id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) ListLeaveBalancesByUser(ctx context.Context, arg ListLeaveBalancesByUserParams) ([]LeaveBalance, error) {
	rows, err := q.db.Query(ctx, listLeaveBalancesByUser, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveBalance
	for rows.Next() {
		var i LeaveBalance
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.LeaveTypeID,
			&i.PeriodYear,
			&i.GrantedHours,
			&i.UsedHours,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaveBalancesByUserYear = `-- name: ListLeaveBalancesByUserYear :many
SELECT id, tenant_id, user_id, leave_type_id, period_year,
       granted_hours, used_hours, expires_at,
       created_at, updated_at
FROM leave_balances
WHERE user_id = $1
  AND tenant_id = $2
  AND period_year = $3
ORDER BY leave_type_id ASC
`

type ListLeaveBalancesByUserYearParams struct {
	UserID     int64 `json:"user_id"`
	TenantID   int64 `json:"tenant_id"`
	PeriodYear int32 `json:"period_year"`
}

func (q *Queries) ListLeaveBalancesByUserYear(ctx context.Context, arg ListLeaveBalancesByUserYearParams) ([]LeaveBalance, error) {
	rows, err := q.db.Query(ctx, listLeaveBalancesByUserYear, arg.UserID, arg.TenantID, arg.PeriodYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveBalance
	for rows.Next() {
		var i LeaveBalance
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.LeaveTypeID,
			&i.PeriodYear,
			&i.GrantedHours,
			&i.UsedHours,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLeaveBalanceGrant = `-- name: UpsertLeaveBalanceGrant :one
INSERT INTO leave_balances (tenant_id, user_id, leave_type_id, period_year,
                            granted_hours, used_hours, expires_at)
VALUES ($1, $2, $3, $4, $5, 0, $6)
ON CONFLICT (user_id, leave_type_id, period_year)
DO UPDATE SET granted_hours = EXCLUDED.granted_hours,
              expires_at = EXCLUDED.expires_at,
              updated_at = now()
RETURNING id, tenant_id, user_id, leave_type_id, period_year,
          granted_hours, used_hours, expires_at,
          created_at, updated_at
`

type UpsertLeaveBalanceGrantParams struct {
	TenantID     int64              `json:"tenant_id"`
	UserID       int64              `json:"user_id"`
	LeaveTypeID  int64              `json:"leave_type_id"`
	PeriodYear   int32              `json:"period_year"`
	GrantedHours pgtype.Numeric     `json:"granted_hours"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertLeaveBalanceGrant(ctx context.Context, arg UpsertLeaveBalanceGrantParams) (LeaveBalance, error) {
	row := q.db.QueryRow(ctx, upsertLeaveBalanceGrant,
		arg.TenantID,
		arg.UserID,
		arg.LeaveTypeID,
		arg.PeriodYear,
		arg.GrantedHours,
		arg.ExpiresAt,
	)
	var i LeaveBalance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.LeaveTypeID,
		&i.PeriodYear,
		&i.GrantedHours,
		&i.UsedHours,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
