// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leave_types.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLeaveTypes = `-- name: CountLeaveTypes :one
SELECT COUNT(*) FROM leave_types
WHERE tenant_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountLeaveTypes(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLeaveTypes, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLeaveType = `-- name: CreateLeaveType :one
INSERT INTO leave_types (tenant_id, code, name, default_hours, accrual_policy, is_paid, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, code, name, default_hours, accrual_policy, is_paid, is_active,
          created_at, updated_at, deleted_at
`

type CreateLeaveTypeParams struct {
	TenantID      int64          `json:"tenant_id"`
	Code          string         `json:"code"`
	Name          string         `json:"name"`
	DefaultHours  pgtype.Numeric `json:"default_hours"`
	AccrualPolicy []byte         `json:"accrual_policy"`
	IsPaid        bool           `json:"is_paid"`
	IsActive      bool           `json:"is_active"`
}

func (q *Queries) CreateLeaveType(ctx context.Context, arg CreateLeaveTypeParams) (LeaveType, error) {
	row := q.db.QueryRow(ctx, createLeaveType,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.DefaultHours,
		arg.AccrualPolicy,
		arg.IsPaid,
		arg.IsActive,
	)
	var i LeaveType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.DefaultHours,
		&i.AccrualPolicy,
		&i.IsPaid,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLeaveTypeByCode = `-- name: GetLeaveTypeByCode :one
SELECT id, tenant_id, code, name, default_hours, accrual_policy, is_paid, is_active,
       created_at, updated_at, deleted_at
FROM leave_types
WHERE code = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type GetLeaveTypeByCodeParams struct {
	Code     string `json:"code"`
	TenantID int64  `json:"tenant_id"`
}

func (q *Queries) GetLeaveTypeByCode(ctx context.Context, arg GetLeaveTypeByCodeParams) (LeaveType, error) {
	row := q.db.QueryRow(ctx, getLeaveTypeByCode, arg.Code, arg.TenantID)
	var i LeaveType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.DefaultHours,
		&i.AccrualPolicy,
		&i.IsPaid,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLeaveTypeByID = `-- name: GetLeaveTypeByID :one
SELECT id, tenant_id, code, name, default_hours, accrual_policy, is_paid, is_active,
       created_at, updated_at, deleted_at
FROM leave_types
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type GetLeaveTypeByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetLeaveTypeByID(ctx context.Context, arg GetLeaveTypeByIDParams) (LeaveType, error) {
	row := q.db.QueryRow(ctx, getLeaveTypeByID, arg.ID, arg.TenantID)
	var i LeaveType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.DefaultHours,
		&i.AccrualPolicy,
		&i.IsPaid,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveLeaveTypes = `-- name: ListActiveLeaveTypes :many
SELECT id, tenant_id, code, name, default_hours, accrual_policy, is_paid, is_active,
       created_at, updated_at, deleted_at
FROM leave_types
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND is_active = TRUE
ORDER BY id ASC
`

func (q *Queries) ListActiveLeaveTypes(ctx context.Context, tenantID int64) ([]LeaveType, error) {
	rows, err := q.db.Query(ctx, listActiveLeaveTypes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveType
	for rows.Next() {
		var i LeaveType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.DefaultHours,
			&i.AccrualPolicy,
			&i.IsPaid,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaveTypes = `-- name: ListLeaveTypes :many
SELECT id, tenant_id, code, name, default_hours, accrual_policy, is_paid, is_active,
       created_at, updated_at, deleted_at
FROM leave_types
WHERE tenant_id = $1
  AND deleted_at IS NULL
ORDER BY id ASC
LIMIT $2 OFFSET $3
`

type ListLeaveTypesParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListLeaveTypes(ctx context.Context, arg ListLeaveTypesParams) ([]LeaveType, error) {
	rows, err := q.db.Query(ctx, listLeaveTypes, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveType
	for rows.Next() {
		var i LeaveType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.DefaultHours,
			&i.AccrualPolicy,
			&i.IsPaid,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLeaveType = `-- name: SoftDeleteLeaveType :exec
UPDATE leave_types
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteLeaveTypeParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) SoftDeleteLeaveType(ctx context.Context, arg SoftDeleteLeaveTypeParams) error {
	_, err := q.db.Exec(ctx, softDeleteLeaveType, arg.ID, arg.TenantID)
	return err
}

const updateLeaveType = `-- name: UpdateLeaveType :one
UPDATE leave_types
SET name = COALESCE($1, name),
    default_hours = COALESCE($2, default_hours),
    accrual_policy = COALESCE($3, accrual_policy),
    is_paid = COALESCE($4, is_paid),
    is_active = COALESCE($5, is_active),
    updated_at = now()
WHERE id = $6
  AND tenant_id = $7
  AND deleted_at IS NULL
RETURNING id, tenant_id, code, name, default_hours, accrual_policy, is_paid, is_active,
          created_at, updated_at, deleted_at
`

type UpdateLeaveTypeParams struct {
	Name          pgtype.Text    `json:"name"`
	DefaultHours  pgtype.Numeric `json:"default_hours"`
	AccrualPolicy []byte         `json:"accrual_policy"`
	IsPaid        pgtype.Bool    `json:"is_paid"`
	IsActive      pgtype.Bool    `json:"is_active"`
	ID            int64          `json:"id"`
	TenantID      int64          `json:"tenant_id"`
}

func (q *Queries) UpdateLeaveType(ctx context.Context, arg UpdateLeaveTypeParams) (LeaveType, error) {
	row := q.db.QueryRow(ctx, updateLeaveType,
		arg.Name,
		arg.DefaultHours,
		arg.AccrualPolicy,
		arg.IsPaid,
		arg.IsActive,
		arg.ID,
		arg.TenantID,
	)
	var i LeaveType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.DefaultHours,
		&i.AccrualPolicy,
		&i.IsPaid,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
