// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leave_requests.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelLeaveRequest = `-- name: CancelLeaveRequest :one
UPDATE leave_requests
SET status = 'cancelled',
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
  AND requester_id = $3
  AND status = 'pending'
RETURNING id, tenant_id, requester_id, leave_type_id, start_at, end_at, hours, reason,
          status, approver_id, decided_at, decision_comment, created_at, updated_at
`

type CancelLeaveRequestParams struct {
	ID          int64 `json:"id"`
	TenantID    int64 `json:"tenant_id"`
	RequesterID int64 `json:"requester_id"`
}

// Cancel — 본인이 pending 상태일 때만. WHERE status='pending' 으로 race 방지.
func (q *Queries) CancelLeaveRequest(ctx context.Context, arg CancelLeaveRequestParams) (LeaveRequest, error) {
	row := q.db.QueryRow(ctx, cancelLeaveRequest, arg.ID, arg.TenantID, arg.RequesterID)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequesterID,
		&i.LeaveTypeID,
		&i.StartAt,
		&i.EndAt,
		&i.Hours,
		&i.Reason,
		&i.Status,
		&i.ApproverID,
		&i.DecidedAt,
		&i.DecisionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countLeaveRequestsByRequester = `-- name: CountLeaveRequestsByRequester :one
SELECT COUNT(*) FROM leave_requests
WHERE requester_id = $1
  AND tenant_id = $2
`

type CountLeaveRequestsByRequesterParams struct {
	RequesterID int64 `json:"requester_id"`
	TenantID    int64 `json:"tenant_id"`
}

func (q *Queries) CountLeaveRequestsByRequester(ctx context.Context, arg CountLeaveRequestsByRequesterParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLeaveRequestsByRequester, arg.RequesterID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingLeaveRequestsByApprover = `-- name: CountPendingLeaveRequestsByApprover :one
SELECT COUNT(*) FROM leave_requests
WHERE approver_id = $1
  AND tenant_id = $2
  AND status = 'pending'
`

type CountPendingLeaveRequestsByApproverParams struct {
	ApproverID pgtype.Int8 `json:"approver_id"`
	TenantID   int64       `json:"tenant_id"`
}

func (q *Queries) CountPendingLeaveRequestsByApprover(ctx context.Context, arg CountPendingLeaveRequestsByApproverParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingLeaveRequestsByApprover, arg.ApproverID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLeaveRequest = `-- name: CreateLeaveRequest :one
INSERT INTO leave_requests (tenant_id, requester_id, leave_type_id, start_at, end_at,
                            hours, reason, approver_id, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending')
RETURNING id, tenant_id, requester_id, leave_type_id, start_at, end_at, hours, reason,
          status, approver_id, decided_at, decision_comment, created_at, updated_at
`

type CreateLeaveRequestParams struct {
	TenantID    int64              `json:"tenant_id"`
	RequesterID int64              `json:"requester_id"`
	LeaveTypeID int64              `json:"leave_type_id"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	Hours       pgtype.Numeric     `json:"hours"`
	Reason      pgtype.Text        `json:"reason"`
	ApproverID  pgtype.Int8        `json:"approver_id"`
}

func (q *Queries) CreateLeaveRequest(ctx context.Context, arg CreateLeaveRequestParams) (LeaveRequest, error) {
	row := q.db.QueryRow(ctx, createLeaveRequest,
		arg.TenantID,
		arg.RequesterID,
		arg.LeaveTypeID,
		arg.StartAt,
		arg.EndAt,
		arg.Hours,
		arg.Reason,
		arg.ApproverID,
	)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequesterID,
		&i.LeaveTypeID,
		&i.StartAt,
		&i.EndAt,
		&i.Hours,
		&i.Reason,
		&i.Status,
		&i.ApproverID,
		&i.DecidedAt,
		&i.DecisionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fetchApprovedLeaveDaysForUsers = `-- name: FetchApprovedLeaveDaysForUsers :many
SELECT lr.id, lr.requester_id, lr.start_at, lr.end_at, lr.hours,
       lt.code AS leave_type_code, lt.default_hours
FROM leave_requests lr
JOIN leave_types lt ON lt.id = lr.leave_type_id AND lt.tenant_id = lr.tenant_id
WHERE lr.requester_id = ANY($1::bigint[])
  AND lr.tenant_id = $2
  AND lr.status = 'approved'
  AND lr.start_at::date <= $3::date
  AND lr.end_at::date >= $4::date
`

type FetchApprovedLeaveDaysForUsersParams struct {
	UserIds  []int64     `json:"user_ids"`
	TenantID int64       `json:"tenant_id"`
	ToDate   pgtype.Date `json:"to_date"`
	FromDate pgtype.Date `json:"from_date"`
}

type FetchApprovedLeaveDaysForUsersRow struct {
	ID            int64              `json:"id"`
	RequesterID   int64              `json:"requester_id"`
	StartAt       pgtype.Timestamptz `json:"start_at"`
	EndAt         pgtype.Timestamptz `json:"end_at"`
	Hours         pgtype.Numeric     `json:"hours"`
	LeaveTypeCode string             `json:"leave_type_code"`
	DefaultHours  pgtype.Numeric     `json:"default_hours"`
}

// Sprint 6 stats integration — Scoped Querier 가 일별 휴가 펼치기 위해 호출.
// approved 상태의 휴가만 통계 보정에 반영.
func (q *Queries) FetchApprovedLeaveDaysForUsers(ctx context.Context, arg FetchApprovedLeaveDaysForUsersParams) ([]FetchApprovedLeaveDaysForUsersRow, error) {
	rows, err := q.db.Query(ctx, fetchApprovedLeaveDaysForUsers,
		arg.UserIds,
		arg.TenantID,
		arg.ToDate,
		arg.FromDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchApprovedLeaveDaysForUsersRow
	for rows.Next() {
		var i FetchApprovedLeaveDaysForUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.StartAt,
			&i.EndAt,
			&i.Hours,
			&i.LeaveTypeCode,
			&i.DefaultHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOverlappingLeaveRequests = `-- name: FindOverlappingLeaveRequests :many
SELECT id, tenant_id, requester_id, leave_type_id, start_at, end_at, hours, reason,
       status, approver_id, decided_at, decision_comment, created_at, updated_at
FROM leave_requests
WHERE requester_id = $1
  AND tenant_id = $2
  AND status IN ('pending', 'approved')
  AND start_at < $4
  AND end_at > $3
`

type FindOverlappingLeaveRequestsParams struct {
	RequesterID int64              `json:"requester_id"`
	TenantID    int64              `json:"tenant_id"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
}

// 같은 사용자, pending|approved 상태에서 [start_at, end_at] 가 겹치는 신청 검색.
// 중복 검증 (DUPLICATE_LEAVE_DATE) 에 사용.
func (q *Queries) FindOverlappingLeaveRequests(ctx context.Context, arg FindOverlappingLeaveRequestsParams) ([]LeaveRequest, error) {
	rows, err := q.db.Query(ctx, findOverlappingLeaveRequests,
		arg.RequesterID,
		arg.TenantID,
		arg.EndAt,
		arg.StartAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveRequest
	for rows.Next() {
		var i LeaveRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RequesterID,
			&i.LeaveTypeID,
			&i.StartAt,
			&i.EndAt,
			&i.Hours,
			&i.Reason,
			&i.Status,
			&i.ApproverID,
			&i.DecidedAt,
			&i.DecisionComment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaveRequestByID = `-- name: GetLeaveRequestByID :one

SELECT id, tenant_id, requester_id, leave_type_id, start_at, end_at, hours, reason,
       status, approver_id, decided_at, decision_comment, created_at, updated_at
FROM leave_requests
WHERE id = $1
  AND tenant_id = $2
`

type GetLeaveRequestByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

// Sprint 6: leave_requests CRUD + 결재 상태 전이 + 잔여 차감 트랜잭션 지원.
func (q *Queries) GetLeaveRequestByID(ctx context.Context, arg GetLeaveRequestByIDParams) (LeaveRequest, error) {
	row := q.db.QueryRow(ctx, getLeaveRequestByID, arg.ID, arg.TenantID)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequesterID,
		&i.LeaveTypeID,
		&i.StartAt,
		&i.EndAt,
		&i.Hours,
		&i.Reason,
		&i.Status,
		&i.ApproverID,
		&i.DecidedAt,
		&i.DecisionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeaveRequestForUpdate = `-- name: GetLeaveRequestForUpdate :one
SELECT id, tenant_id, requester_id, leave_type_id, start_at, end_at, hours, reason,
       status, approver_id, decided_at, decision_comment, created_at, updated_at
FROM leave_requests
WHERE id = $1
  AND tenant_id = $2
FOR UPDATE
`

type GetLeaveRequestForUpdateParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

// Approve/Reject 트랜잭션 내부 — SELECT FOR UPDATE 로 동시성 보호.
func (q *Queries) GetLeaveRequestForUpdate(ctx context.Context, arg GetLeaveRequestForUpdateParams) (LeaveRequest, error) {
	row := q.db.QueryRow(ctx, getLeaveRequestForUpdate, arg.ID, arg.TenantID)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequesterID,
		&i.LeaveTypeID,
		&i.StartAt,
		&i.EndAt,
		&i.Hours,
		&i.Reason,
		&i.Status,
		&i.ApproverID,
		&i.DecidedAt,
		&i.DecisionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementLeaveBalanceUsed = `-- name: IncrementLeaveBalanceUsed :one
INSERT INTO leave_balances (tenant_id, user_id, leave_type_id, period_year,
                            granted_hours, used_hours)
VALUES ($1, $2, $3, $4, 0, $5)
ON CONFLICT (user_id, leave_type_id, period_year)
DO UPDATE SET used_hours = leave_balances.used_hours + EXCLUDED.used_hours,
              updated_at = now()
RETURNING id, tenant_id, user_id, leave_type_id, period_year,
          granted_hours, used_hours, expires_at, created_at, updated_at
`

type IncrementLeaveBalanceUsedParams struct {
	TenantID    int64          `json:"tenant_id"`
	UserID      int64          `json:"user_id"`
	LeaveTypeID int64          `json:"leave_type_id"`
	PeriodYear  int32          `json:"period_year"`
	UsedHours   pgtype.Numeric `json:"used_hours"`
}

// Approve 트랜잭션 내부 — UPSERT 로 잔여 row 없으면 0 granted 로 생성 + used += hours.
func (q *Queries) IncrementLeaveBalanceUsed(ctx context.Context, arg IncrementLeaveBalanceUsedParams) (LeaveBalance, error) {
	row := q.db.QueryRow(ctx, incrementLeaveBalanceUsed,
		arg.TenantID,
		arg.UserID,
		arg.LeaveTypeID,
		arg.PeriodYear,
		arg.UsedHours,
	)
	var i LeaveBalance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.LeaveTypeID,
		&i.PeriodYear,
		&i.GrantedHours,
		&i.UsedHours,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLeaveRequestsByRequester = `-- name: ListLeaveRequestsByRequester :many
SELECT id, tenant_id, requester_id, leave_type_id, start_at, end_at, hours, reason,
       status, approver_id, decided_at, decision_comment, created_at, updated_at
FROM leave_requests
WHERE requester_id = $1
  AND tenant_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListLeaveRequestsByRequesterParams struct {
	RequesterID int64 `json:"requester_id"`
	TenantID    int64 `json:"tenant_id"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

func (q *Queries) ListLeaveRequestsByRequester(ctx context.Context, arg ListLeaveRequestsByRequesterParams) ([]LeaveRequest, error) {
	rows, err := q.db.Query(ctx, listLeaveRequestsByRequester,
		arg.RequesterID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveRequest
	for rows.Next() {
		var i LeaveRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RequesterID,
			&i.LeaveTypeID,
			&i.StartAt,
			&i.EndAt,
			&i.Hours,
			&i.Reason,
			&i.Status,
			&i.ApproverID,
			&i.DecidedAt,
			&i.DecisionComment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingLeaveRequestsByApprover = `-- name: ListPendingLeaveRequestsByApprover :many
SELECT id, tenant_id, requester_id, leave_type_id, start_at, end_at, hours, reason,
       status, approver_id, decided_at, decision_comment, created_at, updated_at
FROM leave_requests
WHERE approver_id = $1
  AND tenant_id = $2
  AND status = 'pending'
ORDER BY created_at ASC, id ASC
LIMIT $3 OFFSET $4
`

type ListPendingLeaveRequestsByApproverParams struct {
	ApproverID pgtype.Int8 `json:"approver_id"`
	TenantID   int64       `json:"tenant_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

// 결재자 대기함. approver_id 매칭 + status='pending'.
func (q *Queries) ListPendingLeaveRequestsByApprover(ctx context.Context, arg ListPendingLeaveRequestsByApproverParams) ([]LeaveRequest, error) {
	rows, err := q.db.Query(ctx, listPendingLeaveRequestsByApprover,
		arg.ApproverID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveRequest
	for rows.Next() {
		var i LeaveRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RequesterID,
			&i.LeaveTypeID,
			&i.StartAt,
			&i.EndAt,
			&i.Hours,
			&i.Reason,
			&i.Status,
			&i.ApproverID,
			&i.DecidedAt,
			&i.DecisionComment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLeaveRequestDecision = `-- name: UpdateLeaveRequestDecision :one
UPDATE leave_requests
SET status = $3,
    approver_id = $4,
    decided_at = $5,
    decision_comment = $6,
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, requester_id, leave_type_id, start_at, end_at, hours, reason,
          status, approver_id, decided_at, decision_comment, created_at, updated_at
`

type UpdateLeaveRequestDecisionParams struct {
	ID              int64              `json:"id"`
	TenantID        int64              `json:"tenant_id"`
	Status          LeaveRequestStatus `json:"status"`
	ApproverID      pgtype.Int8        `json:"approver_id"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	DecisionComment pgtype.Text        `json:"decision_comment"`
}

// Approve/Reject 공용 — status + approver_id + decided_at + decision_comment 업데이트.
func (q *Queries) UpdateLeaveRequestDecision(ctx context.Context, arg UpdateLeaveRequestDecisionParams) (LeaveRequest, error) {
	row := q.db.QueryRow(ctx, updateLeaveRequestDecision,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.ApproverID,
		arg.DecidedAt,
		arg.DecisionComment,
	)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequesterID,
		&i.LeaveTypeID,
		&i.StartAt,
		&i.EndAt,
		&i.Hours,
		&i.Reason,
		&i.Status,
		&i.ApproverID,
		&i.DecidedAt,
		&i.DecisionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
