// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AttendanceSource string

const (
	AttendanceSourceButton           AttendanceSource = "button"
	AttendanceSourceManualCorrection AttendanceSource = "manual_correction"
)

func (e *AttendanceSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttendanceSource(s)
	case string:
		*e = AttendanceSource(s)
	default:
		return fmt.Errorf("unsupported scan type for AttendanceSource: %T", src)
	}
	return nil
}

type NullAttendanceSource struct {
	AttendanceSource AttendanceSource `json:"attendance_source"`
	Valid            bool             `json:"valid"` // Valid is true if AttendanceSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttendanceSource) Scan(value interface{}) error {
	if value == nil {
		ns.AttendanceSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttendanceSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttendanceSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttendanceSource), nil
}

type AttendanceStatus string

const (
	AttendanceStatusNormal     AttendanceStatus = "normal"
	AttendanceStatusLate       AttendanceStatus = "late"
	AttendanceStatusEarlyLeave AttendanceStatus = "early_leave"
	AttendanceStatusAbsent     AttendanceStatus = "absent"
	AttendanceStatusAutoClosed AttendanceStatus = "auto_closed"
)

func (e *AttendanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttendanceStatus(s)
	case string:
		*e = AttendanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AttendanceStatus: %T", src)
	}
	return nil
}

type NullAttendanceStatus struct {
	AttendanceStatus AttendanceStatus `json:"attendance_status"`
	Valid            bool             `json:"valid"` // Valid is true if AttendanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttendanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AttendanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttendanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttendanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttendanceStatus), nil
}

type LeaveRequestStatus string

const (
	LeaveRequestStatusPending   LeaveRequestStatus = "pending"
	LeaveRequestStatusApproved  LeaveRequestStatus = "approved"
	LeaveRequestStatusRejected  LeaveRequestStatus = "rejected"
	LeaveRequestStatusCancelled LeaveRequestStatus = "cancelled"
)

func (e *LeaveRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeaveRequestStatus(s)
	case string:
		*e = LeaveRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LeaveRequestStatus: %T", src)
	}
	return nil
}

type NullLeaveRequestStatus struct {
	LeaveRequestStatus LeaveRequestStatus `json:"leave_request_status"`
	Valid              bool               `json:"valid"` // Valid is true if LeaveRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeaveRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LeaveRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeaveRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeaveRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeaveRequestStatus), nil
}

type UserRole string

const (
	UserRoleGeneral    UserRole = "general"
	UserRoleTeamLead   UserRole = "team_lead"
	UserRoleDeptHead   UserRole = "dept_head"
	UserRoleHrManager  UserRole = "hr_manager"
	UserRoleSuperAdmin UserRole = "super_admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusActive     UserStatus = "active"
	UserStatusInactive   UserStatus = "inactive"
	UserStatusTerminated UserStatus = "terminated"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AttendanceRecord struct {
	ID                int64              `json:"id"`
	TenantID          int64              `json:"tenant_id"`
	UserID            int64              `json:"user_id"`
	WorkDate          pgtype.Date        `json:"work_date"`
	CheckInAt         pgtype.Timestamptz `json:"check_in_at"`
	CheckOutAt        pgtype.Timestamptz `json:"check_out_at"`
	LunchBreakMinutes int32              `json:"lunch_break_minutes"`
	Source            AttendanceSource   `json:"source"`
	ClientIp          *netip.Addr        `json:"client_ip"`
	UserAgent         pgtype.Text        `json:"user_agent"`
	Status            AttendanceStatus   `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Delegation struct {
	ID          int64              `json:"id"`
	TenantID    int64              `json:"tenant_id"`
	DelegatorID int64              `json:"delegator_id"`
	DelegateID  int64              `json:"delegate_id"`
	ValidFrom   pgtype.Timestamptz `json:"valid_from"`
	ValidTo     pgtype.Timestamptz `json:"valid_to"`
	Scope       []byte             `json:"scope"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ExpenseReport struct {
	ID              int64              `json:"id"`
	TenantID        int64              `json:"tenant_id"`
	RequesterID     int64              `json:"requester_id"`
	AmountWon       int64              `json:"amount_won"`
	Vendor          string             `json:"vendor"`
	Purpose         string             `json:"purpose"`
	PaidAt          pgtype.Date        `json:"paid_at"`
	AttachmentUrl   pgtype.Text        `json:"attachment_url"`
	Status          LeaveRequestStatus `json:"status"`
	ApproverID      pgtype.Int8        `json:"approver_id"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	DecisionComment pgtype.Text        `json:"decision_comment"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Holiday struct {
	ID          int64              `json:"id"`
	TenantID    int64              `json:"tenant_id"`
	Date        pgtype.Date        `json:"date"`
	Name        string             `json:"name"`
	IsRecurring bool               `json:"is_recurring"`
	CountryCode string             `json:"country_code"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type LeaveBalance struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	UserID       int64              `json:"user_id"`
	LeaveTypeID  int64              `json:"leave_type_id"`
	PeriodYear   int32              `json:"period_year"`
	GrantedHours pgtype.Numeric     `json:"granted_hours"`
	UsedHours    pgtype.Numeric     `json:"used_hours"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type LeaveBalanceAdjustment struct {
	ID          int64              `json:"id"`
	TenantID    int64              `json:"tenant_id"`
	BalanceID   int64              `json:"balance_id"`
	ActorUserID int64              `json:"actor_user_id"`
	DeltaHours  pgtype.Numeric     `json:"delta_hours"`
	Reason      string             `json:"reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type LeaveRequest struct {
	ID              int64              `json:"id"`
	TenantID        int64              `json:"tenant_id"`
	RequesterID     int64              `json:"requester_id"`
	LeaveTypeID     int64              `json:"leave_type_id"`
	StartAt         pgtype.Timestamptz `json:"start_at"`
	EndAt           pgtype.Timestamptz `json:"end_at"`
	Hours           pgtype.Numeric     `json:"hours"`
	Reason          pgtype.Text        `json:"reason"`
	Status          LeaveRequestStatus `json:"status"`
	ApproverID      pgtype.Int8        `json:"approver_id"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	DecisionComment pgtype.Text        `json:"decision_comment"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type LeaveType struct {
	ID            int64              `json:"id"`
	TenantID      int64              `json:"tenant_id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	DefaultHours  pgtype.Numeric     `json:"default_hours"`
	AccrualPolicy []byte             `json:"accrual_policy"`
	IsPaid        bool               `json:"is_paid"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type Notification struct {
	ID         int64              `json:"id"`
	TenantID   int64              `json:"tenant_id"`
	UserID     int64              `json:"user_id"`
	Type       string             `json:"type"`
	Title      string             `json:"title"`
	Body       string             `json:"body"`
	RelatedUrl pgtype.Text        `json:"related_url"`
	ReadAt     pgtype.Timestamptz `json:"read_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	Jti       pgtype.UUID        `json:"jti"`
	UserID    int64              `json:"user_id"`
	TenantID  int64              `json:"tenant_id"`
	IssuedAt  pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type Team struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	Name         string             `json:"name"`
	ParentTeamID pgtype.Int8        `json:"parent_team_id"`
	TeamLeadID   pgtype.Int8        `json:"team_lead_id"`
	HrManagerID  pgtype.Int8        `json:"hr_manager_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID            int64              `json:"id"`
	TenantID      int64              `json:"tenant_id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	Name          string             `json:"name"`
	Status        UserStatus         `json:"status"`
	TeamID        pgtype.Int8        `json:"team_id"`
	ManagerID     pgtype.Int8        `json:"manager_id"`
	HireDate      pgtype.Date        `json:"hire_date"`
	Role          UserRole           `json:"role"`
	WorkStartTime pgtype.Time        `json:"work_start_time"`
	WorkEndTime   pgtype.Time        `json:"work_end_time"`
	TokenVersion  int32              `json:"token_version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
