// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationsForUser = `-- name: CountNotificationsForUser :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1
  AND tenant_id = $2
`

type CountNotificationsForUserParams struct {
	UserID   int64 `json:"user_id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) CountNotificationsForUser(ctx context.Context, arg CountNotificationsForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsForUser, arg.UserID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotificationsForUser = `-- name: CountUnreadNotificationsForUser :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1
  AND tenant_id = $2
  AND read_at IS NULL
`

type CountUnreadNotificationsForUserParams struct {
	UserID   int64 `json:"user_id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) CountUnreadNotificationsForUser(ctx context.Context, arg CountUnreadNotificationsForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotificationsForUser, arg.UserID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (tenant_id, user_id, type, title, body, related_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, user_id, type, title, body, related_url, read_at, created_at
`

type CreateNotificationParams struct {
	TenantID   int64       `json:"tenant_id"`
	UserID     int64       `json:"user_id"`
	Type       string      `json:"type"`
	Title      string      `json:"title"`
	Body       string      `json:"body"`
	RelatedUrl pgtype.Text `json:"related_url"`
}

// Sprint 8: notifications CRUD + read 처리.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.TenantID,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.RelatedUrl,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.RelatedUrl,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, tenant_id, user_id, type, title, body, related_url, read_at, created_at
FROM notifications
WHERE id = $1
  AND tenant_id = $2
`

type GetNotificationByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, arg.ID, arg.TenantID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.RelatedUrl,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, tenant_id, user_id, type, title, body, related_url, read_at, created_at
FROM notifications
WHERE user_id = $1
  AND tenant_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListNotificationsForUserParams struct {
	UserID   int64 `json:"user_id"`
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForUser,
		arg.UserID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.RelatedUrl,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotificationsForUser = `-- name: ListUnreadNotificationsForUser :many
SELECT id, tenant_id, user_id, type, title, body, related_url, read_at, created_at
FROM notifications
WHERE user_id = $1
  AND tenant_id = $2
  AND read_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListUnreadNotificationsForUserParams struct {
	UserID   int64 `json:"user_id"`
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListUnreadNotificationsForUser(ctx context.Context, arg ListUnreadNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotificationsForUser,
		arg.UserID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.RelatedUrl,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
SET read_at = now()
WHERE user_id = $1
  AND tenant_id = $2
  AND read_at IS NULL
`

type MarkAllNotificationsReadParams struct {
	UserID   int64 `json:"user_id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, arg.UserID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET read_at = COALESCE(read_at, now())
WHERE id = $1
  AND tenant_id = $2
  AND user_id = $3
RETURNING id, tenant_id, user_id, type, title, body, related_url, read_at, created_at
`

type MarkNotificationReadParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
	UserID   int64 `json:"user_id"`
}

// 본인 알림만 + 미읽음일 때만 read_at = now() 로 갱신.
// 이미 읽음 처리된 row 는 read_at 을 보존 (멱등).
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.TenantID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.RelatedUrl,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}
