// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (jti, user_id, tenant_id, issued_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRefreshTokenParams struct {
	Jti       pgtype.UUID        `json:"jti"`
	UserID    int64              `json:"user_id"`
	TenantID  int64              `json:"tenant_id"`
	IssuedAt  pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.Jti,
		arg.UserID,
		arg.TenantID,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, expiresAt)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT jti, user_id, tenant_id, issued_at, expires_at, used_at
FROM refresh_tokens
WHERE jti = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, jti pgtype.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, jti)
	var i RefreshToken
	err := row.Scan(
		&i.Jti,
		&i.UserID,
		&i.TenantID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :one
UPDATE refresh_tokens
SET used_at = now()
WHERE jti = $1
  AND used_at IS NULL
RETURNING jti, user_id, tenant_id, issued_at, expires_at, used_at
`

// 1회용 회전: used_at IS NULL 인 경우에만 마킹 성공. 이미 used 인 경우 0 rows.
// 호출자가 RETURNING 결과로 0 rows 여부를 판단해 reuse 감지를 수행한다.
func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, jti pgtype.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, markRefreshTokenUsed, jti)
	var i RefreshToken
	err := row.Scan(
		&i.Jti,
		&i.UserID,
		&i.TenantID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}
