// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTeams = `-- name: CountTeams :one
SELECT COUNT(*) FROM teams
WHERE tenant_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountTeams(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTeams, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (tenant_id, name, parent_team_id, team_lead_id, hr_manager_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, parent_team_id, team_lead_id, hr_manager_id,
          created_at, updated_at, deleted_at
`

type CreateTeamParams struct {
	TenantID     int64       `json:"tenant_id"`
	Name         string      `json:"name"`
	ParentTeamID pgtype.Int8 `json:"parent_team_id"`
	TeamLeadID   pgtype.Int8 `json:"team_lead_id"`
	HrManagerID  pgtype.Int8 `json:"hr_manager_id"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.TenantID,
		arg.Name,
		arg.ParentTeamID,
		arg.TeamLeadID,
		arg.HrManagerID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ParentTeamID,
		&i.TeamLeadID,
		&i.HrManagerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, tenant_id, name, parent_team_id, team_lead_id, hr_manager_id,
       created_at, updated_at, deleted_at
FROM teams
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type GetTeamByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetTeamByID(ctx context.Context, arg GetTeamByIDParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, arg.ID, arg.TenantID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ParentTeamID,
		&i.TeamLeadID,
		&i.HrManagerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id, tenant_id, name, parent_team_id, team_lead_id, hr_manager_id,
       created_at, updated_at, deleted_at
FROM teams
WHERE tenant_id = $1
  AND deleted_at IS NULL
ORDER BY id ASC
LIMIT $2 OFFSET $3
`

type ListTeamsParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListTeams(ctx context.Context, arg ListTeamsParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ParentTeamID,
			&i.TeamLeadID,
			&i.HrManagerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTeam = `-- name: SoftDeleteTeam :exec
UPDATE teams
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteTeamParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) SoftDeleteTeam(ctx context.Context, arg SoftDeleteTeamParams) error {
	_, err := q.db.Exec(ctx, softDeleteTeam, arg.ID, arg.TenantID)
	return err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name = COALESCE($1, name),
    parent_team_id = CASE WHEN $2::bool THEN $3 ELSE parent_team_id END,
    team_lead_id = CASE WHEN $4::bool THEN $5 ELSE team_lead_id END,
    hr_manager_id = CASE WHEN $6::bool THEN $7 ELSE hr_manager_id END,
    updated_at = now()
WHERE id = $8
  AND tenant_id = $9
  AND deleted_at IS NULL
RETURNING id, tenant_id, name, parent_team_id, team_lead_id, hr_manager_id,
          created_at, updated_at, deleted_at
`

type UpdateTeamParams struct {
	Name         pgtype.Text `json:"name"`
	ParentSet    bool        `json:"parent_set"`
	ParentTeamID pgtype.Int8 `json:"parent_team_id"`
	LeadSet      bool        `json:"lead_set"`
	TeamLeadID   pgtype.Int8 `json:"team_lead_id"`
	HrSet        bool        `json:"hr_set"`
	HrManagerID  pgtype.Int8 `json:"hr_manager_id"`
	ID           int64       `json:"id"`
	TenantID     int64       `json:"tenant_id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.Name,
		arg.ParentSet,
		arg.ParentTeamID,
		arg.LeadSet,
		arg.TeamLeadID,
		arg.HrSet,
		arg.HrManagerID,
		arg.ID,
		arg.TenantID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ParentTeamID,
		&i.TeamLeadID,
		&i.HrManagerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
