// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE tenant_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, password_hash, name, hire_date, role, team_id, manager_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, email, password_hash, name, status, team_id, manager_id,
          hire_date, role, work_start_time, work_end_time, token_version,
          created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	TenantID     int64       `json:"tenant_id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         string      `json:"name"`
	HireDate     pgtype.Date `json:"hire_date"`
	Role         UserRole    `json:"role"`
	TeamID       pgtype.Int8 `json:"team_id"`
	ManagerID    pgtype.Int8 `json:"manager_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.HireDate,
		arg.Role,
		arg.TeamID,
		arg.ManagerID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.TeamID,
		&i.ManagerID,
		&i.HireDate,
		&i.Role,
		&i.WorkStartTime,
		&i.WorkEndTime,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, name, status, team_id, manager_id,
       hire_date, role, work_start_time, work_end_time, token_version,
       created_at, updated_at, deleted_at
FROM users
WHERE email = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type GetUserByEmailParams struct {
	Email    string `json:"email"`
	TenantID int64  `json:"tenant_id"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.TeamID,
		&i.ManagerID,
		&i.HireDate,
		&i.Role,
		&i.WorkStartTime,
		&i.WorkEndTime,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, name, status, team_id, manager_id,
       hire_date, role, work_start_time, work_end_time, token_version,
       created_at, updated_at, deleted_at
FROM users
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type GetUserByIDParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.TeamID,
		&i.ManagerID,
		&i.HireDate,
		&i.Role,
		&i.WorkStartTime,
		&i.WorkEndTime,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserTokenVersion = `-- name: GetUserTokenVersion :one
SELECT token_version, status, role
FROM users
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type GetUserTokenVersionParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

type GetUserTokenVersionRow struct {
	TokenVersion int32      `json:"token_version"`
	Status       UserStatus `json:"status"`
	Role         UserRole   `json:"role"`
}

func (q *Queries) GetUserTokenVersion(ctx context.Context, arg GetUserTokenVersionParams) (GetUserTokenVersionRow, error) {
	row := q.db.QueryRow(ctx, getUserTokenVersion, arg.ID, arg.TenantID)
	var i GetUserTokenVersionRow
	err := row.Scan(&i.TokenVersion, &i.Status, &i.Role)
	return i, err
}

const incrementUserTokenVersion = `-- name: IncrementUserTokenVersion :one
UPDATE users
SET token_version = token_version + 1,
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
RETURNING token_version
`

type IncrementUserTokenVersionParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) IncrementUserTokenVersion(ctx context.Context, arg IncrementUserTokenVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementUserTokenVersion, arg.ID, arg.TenantID)
	var token_version int32
	err := row.Scan(&token_version)
	return token_version, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, email, password_hash, name, status, team_id, manager_id,
       hire_date, role, work_start_time, work_end_time, token_version,
       created_at, updated_at, deleted_at
FROM users
WHERE tenant_id = $1
  AND deleted_at IS NULL
ORDER BY id ASC
LIMIT $2 OFFSET $3
`

type ListUsersParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Status,
			&i.TeamID,
			&i.ManagerID,
			&i.HireDate,
			&i.Role,
			&i.WorkStartTime,
			&i.WorkEndTime,
			&i.TokenVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = COALESCE($1, name),
    role = COALESCE($2, role),
    team_id = CASE WHEN $3::bool THEN $4 ELSE team_id END,
    manager_id = CASE WHEN $5::bool THEN $6 ELSE manager_id END,
    status = COALESCE($7, status),
    updated_at = now()
WHERE id = $8
  AND tenant_id = $9
  AND deleted_at IS NULL
RETURNING id, tenant_id, email, password_hash, name, status, team_id, manager_id,
          hire_date, role, work_start_time, work_end_time, token_version,
          created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	Name         pgtype.Text    `json:"name"`
	Role         NullUserRole   `json:"role"`
	TeamIDSet    bool           `json:"team_id_set"`
	TeamID       pgtype.Int8    `json:"team_id"`
	ManagerIDSet bool           `json:"manager_id_set"`
	ManagerID    pgtype.Int8    `json:"manager_id"`
	Status       NullUserStatus `json:"status"`
	ID           int64          `json:"id"`
	TenantID     int64          `json:"tenant_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Role,
		arg.TeamIDSet,
		arg.TeamID,
		arg.ManagerIDSet,
		arg.ManagerID,
		arg.Status,
		arg.ID,
		arg.TenantID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.TeamID,
		&i.ManagerID,
		&i.HireDate,
		&i.Role,
		&i.WorkStartTime,
		&i.WorkEndTime,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
