apiVersion: v1
kind: Service
metadata:
  name: inspection-service
  labels:
    app: inspection-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4002
      targetPort: 4002
    - name: grpc
      port: 5002
      targetPort: 5002
  selector:
    app: inspection-service
