apiVersion: v1
kind: Secret
metadata:
  name: trustee-secrets
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk        # rootpassword
  mysql-user: dHJ1c3RlZQ==                      # trustee
  mysql-password: dHJ1c3RlZXBhc3N3b3Jk          # trusteepassword
  rabbitmq-user: dHJ1c3RlZQ==                   # trustee
  rabbitmq-password: dHJ1c3RlZXBhc3N3b3Jk       # trusteepassword
